spring:
  flyway:
    baseline-on-migrate: true
    enabled: ${MIGRATIONS_ENABLED:true}
    locations: classpath:/db/migration
    url: jdbc:h2:file:./testdb
    user: sa
  r2dbc:
    driver: io.r2dbc.h2.H2ConnectionConfiguration
    url: r2dbc:h2:file:///./testdb
    username: sa
